import { Badge } from "@cloudflare/kumo/components/badge";
import { Button } from "@cloudflare/kumo/components/button";
import { Dialog } from "@cloudflare/kumo/components/dialog";
import { LayerCard } from "@cloudflare/kumo/components/layer-card";
import { ArrowLeft, Trash, WarningCircle, X } from "@phosphor-icons/react";
import { createFileRoute, Link, notFound, useRouter } from "@tanstack/react-router";
import { startTransition, useEffect, useState } from "react";

import { AcademicToast } from "../components/academic/academic-feedback";
import { AcademicShell } from "../components/academic/academic-shell";
import { CourseForm, type CourseFormValues } from "../components/academic/course-form";
import type { AcademicFieldError, Course } from "../server/academic/domain";
import { archiveCourse, deleteCourse, getCourse, reopenCourse, undoAcademicCommand, updateCourse } from "../server/academic/functions";
import { requireAuthenticatedRoute } from "../server/auth/functions";

export const Route = createFileRoute("/courses_/$courseId")({ beforeLoad: requireAuthenticatedRoute, loader: async ({ params }) => { const course = await getCourse({ data: params.courseId }); if (!isCourse(course)) throw notFound(); return course; }, component: CourseDetailRoute, notFoundComponent: () => <AcademicShell><main className="mx-auto max-w-3xl px-4 py-12"><h1 className="text-2xl font-semibold">Course not found</h1><Link to="/courses" className="mt-5 inline-flex min-h-11 items-center text-sm font-medium text-kumo-brand">Back to courses</Link></main></AcademicShell> });

function CourseDetailRoute() {
  const course = Route.useLoaderData(); const navigate = Route.useNavigate(); const router = useRouter();
  const [editOpen, setEditOpen] = useState(false); const [deleteOpen, setDeleteOpen] = useState(false); const [pending, setPending] = useState(false); const [errors, setErrors] = useState<ReadonlyArray<AcademicFieldError>>([]); const [notice, setNotice] = useState<{ readonly message: string; readonly token?: string }>();
  useEffect(() => { const stored = sessionStorage.getItem("kairo.academic.notice"); if (!stored) return; sessionStorage.removeItem("kairo.academic.notice"); try { const value: unknown = JSON.parse(stored); if (value && typeof value === "object" && "message" in value && typeof value.message === "string") { const token = Reflect.get(value, "token"); setNotice({ message: value.message, ...(typeof token === "string" ? { token } : {}) }); } } catch { /* Ignore stale route feedback. */ } }, []);
  const refresh = () => startTransition(() => void router.invalidate());
  const update = async (values: CourseFormValues) => { setPending(true); setErrors([]); try { const result = await updateCourse({ data: { courseId: course.id, expectedVersion: course.version, patch: { title: values.title, code: values.code }, idempotencyKey: values.idempotencyKey } }); if (result._tag === "invalid") setErrors(result.fields); else if (result._tag === "conflict") setErrors([{ field: "form", message: "This course changed. Reload to see the current values; your edits remain here." }]); else if (result._tag === "applied" || result._tag === "already_applied") { setEditOpen(false); setNotice({ message: "Course updated.", token: result.undoToken }); refresh(); } else setErrors([{ field: "form", message: "The course could not be saved." }]); } finally { setPending(false); } };
  const lifecycle = async () => { setPending(true); try { const fn = course.lifecycle === "current" ? archiveCourse : reopenCourse; const result = await fn({ data: { courseId: course.id, expectedVersion: course.version, idempotencyKey: crypto.randomUUID() } }); if (result._tag === "applied" || result._tag === "already_applied") { setNotice({ message: course.lifecycle === "current" ? "Course archived." : "Course reopened.", token: result.undoToken }); refresh(); } else setNotice({ message: result._tag === "conflict" ? "This course changed. Reload before trying again." : "The course could not be changed." }); } finally { setPending(false); } };
  const remove = async () => { setPending(true); try { const result = await deleteCourse({ data: { courseId: course.id, expectedVersion: course.version, idempotencyKey: crypto.randomUUID() } }); if (result._tag === "applied" || result._tag === "already_applied") { sessionStorage.setItem("kairo.academic.notice", JSON.stringify({ message: "Course deleted.", token: result.undoToken })); await navigate({ to: "/courses" }); } else setNotice({ message: result._tag === "conflict" && result.reason === "has_dependents" ? "Move or delete linked work before deleting this course." : "The course could not be deleted." }); } finally { setPending(false); } };
  const undo = async () => { if (!notice?.token) return; const result = await undoAcademicCommand({ data: { token: notice.token, idempotencyKey: crypto.randomUUID() } }); setNotice({ message: result._tag === "applied" ? "Change undone." : "This change can no longer be undone. Reload to see current data." }); if (result._tag === "applied") refresh(); };
  return <AcademicShell><main className="mx-auto max-w-4xl px-4 py-6 pb-24 sm:px-6 md:py-8 lg:px-10"><Link to="/courses" className="inline-flex min-h-11 items-center gap-2 text-sm font-medium text-kumo-brand"><ArrowLeft aria-hidden="true" size={16} />Back to courses</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold text-kumo-strong">{course.title}</h1><Badge variant="secondary">{course.lifecycle}</Badge></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => setEditOpen(true)}>Edit</Button><Button variant="secondary" disabled={pending} onClick={() => void lifecycle()}>{course.lifecycle === "current" ? "Archive" : "Reopen"}</Button><Button variant="secondary" icon={<Trash aria-hidden="true" size={16} />} onClick={() => setDeleteOpen(true)}>Delete</Button></div></div><LayerCard className="mt-7 px-5 py-5"><h2 className="text-base font-semibold">Course details</h2><dl className="mt-4 grid gap-4 text-sm"><div><dt className="text-kumo-subtle">Code</dt><dd className="mt-1 font-medium">{course.code ?? "No code"}</dd></div><div><dt className="text-kumo-subtle">Updated</dt><dd className="mt-1"><time dateTime={course.updatedAt}>{new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(course.updatedAt))}</time></dd></div></dl></LayerCard>
    <Dialog.Root open={editOpen} onOpenChange={setEditOpen}><Dialog className="p-5 sm:max-w-xl sm:p-6"><div className="mb-5 flex items-center justify-between"><Dialog.Title className="text-xl font-semibold">Edit course</Dialog.Title><Dialog.Close aria-label="Close edit course" render={(props) => <Button {...props} title="Close edit course" variant="secondary" shape="square" icon={<X aria-hidden="true" size={18} />} />} /></div><CourseForm course={course} errors={errors} pending={pending} onCancel={() => setEditOpen(false)} onSubmit={update} /></Dialog></Dialog.Root>
    <Dialog.Root open={deleteOpen} onOpenChange={setDeleteOpen}><Dialog className="p-5 sm:max-w-md sm:p-6"><WarningCircle aria-hidden="true" size={24} className="text-kumo-danger" /><Dialog.Title className="mt-3 text-xl font-semibold">Delete {course.title}?</Dialog.Title><Dialog.Description className="mt-2 text-sm text-kumo-subtle">The course will be removed from academic routes.</Dialog.Description><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={() => setDeleteOpen(false)}>Cancel</Button><Button disabled={pending} onClick={() => void remove()}>Delete course</Button></div></Dialog></Dialog.Root></main>{notice ? <AcademicToast message={notice.message} undoToken={notice.token} pending={pending} onUndo={() => void undo()} /> : null}</AcademicShell>;
}

function isCourse(value: unknown): value is Course { return typeof value === "object" && value !== null && "lifecycle" in value && "version" in value; }
