import { Badge } from "@cloudflare/kumo/components/badge";
import { Button } from "@cloudflare/kumo/components/button";
import { Dialog } from "@cloudflare/kumo/components/dialog";
import { Input } from "@cloudflare/kumo/components/input";
import { LayerCard } from "@cloudflare/kumo/components/layer-card";
import { CalendarCheck, Check, Clock, FunnelSimple, MagnifyingGlass, Plus, Trash, WarningCircle, X } from "@phosphor-icons/react";
import { createFileRoute, Link, useRouter } from "@tanstack/react-router";
import { startTransition, useEffect, useState } from "react";
import { z } from "zod";

import { AcademicError, AcademicLoading, AcademicToast } from "../components/academic/academic-feedback";
import { AcademicForm, type AcademicFormValues } from "../components/academic/academic-form";
import { AcademicShell } from "../components/academic/academic-shell";
import type { AcademicFieldError, AcademicStatus, Assessment, AssessmentOption, CourseOption, Deadline } from "../server/academic/domain";
import { createAssessment, createTask, deleteAssessment, deleteTask, getAcademicWorkloadRange, getAssessment, listAssessmentOptions, listCourseOptions, listDeadlines, setAssessmentStatus, setTaskStatus, undoAcademicCommand, updateAssessment } from "../server/academic/functions";
import { requireAuthenticatedRoute } from "../server/auth/functions";

const isoDate = /^\d{4}-\d{2}-\d{2}$/;
const searchSchema = z.object({ q: z.string().max(100).optional().catch(undefined), kind: z.enum(["all", "task", "assessment"]).optional().catch("all"), status: z.enum(["open", "completed", "cancelled", "all"]).optional().catch("open"), courseId: z.string().uuid().optional().catch(undefined), from: z.string().regex(isoDate).optional().catch(undefined), to: z.string().regex(isoDate).optional().catch(undefined), includeOverdue: z.union([z.boolean(), z.enum(["true", "false"])]).transform((value) => value === true || value === "true").optional().catch(true), pageSize: z.coerce.number().pipe(z.union([z.literal(10), z.literal(25), z.literal(50), z.literal(100)])).optional().catch(25), cursor: z.string().max(2048).optional().catch(undefined) });
const plusDays = (value: string, days: number) => { const date = new Date(`${value}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); };

export const Route = createFileRoute("/deadlines")({
  beforeLoad: requireAuthenticatedRoute,
  validateSearch: searchSchema,
  loaderDeps: ({ search }) => search,
  loader: async ({ deps }) => { const defaultRange = await getAcademicWorkloadRange(); const from = deps.from ?? defaultRange.from; const to = deps.to && deps.to >= from ? deps.to : deps.from ? plusDays(from, 6) : defaultRange.to; const [page, courseResult, assessmentResult] = await Promise.all([listDeadlines({ data: { q: deps.q?.trim() ?? "", kind: deps.kind ?? "all", status: deps.status ?? "open", courseId: deps.courseId ?? null, from, to, includeOverdue: deps.includeOverdue ?? true, pageSize: deps.pageSize ?? 25, cursor: deps.cursor ?? null } }), listCourseOptions(), listAssessmentOptions()]); return { page, courses: isCourseOptions(courseResult) ? courseResult : [], assessments: isAssessmentOptions(assessmentResult) ? assessmentResult : [], from, to, timeZone: defaultRange.timeZone }; },
  pendingComponent: () => <AcademicLoading title="Deadlines" />,
  errorComponent: ({ reset }) => <AcademicError title="Deadlines unavailable" reset={reset} />,
  component: DeadlinesRoute,
});

function DeadlinesRoute() {
  const { page, courses, assessments, from, to, timeZone } = Route.useLoaderData(); const search = Route.useSearch(); const navigate = Route.useNavigate(); const router = useRouter();
  const [createOpen, setCreateOpen] = useState(false); const [createKind, setCreateKind] = useState<"task" | "assessment">("task"); const [selected, setSelected] = useState<Assessment>(); const [deleteRow, setDeleteRow] = useState<Deadline>(); const [pending, setPending] = useState(false); const [errors, setErrors] = useState<ReadonlyArray<AcademicFieldError>>([]); const [notice, setNotice] = useState<{ readonly message: string; readonly token?: string }>();
  const [filters, setFilters] = useState(search); const [rows, setRows] = useState(page.items);
  useEffect(() => setFilters(search), [search]); useEffect(() => setRows(page.items), [page.items]);
  const refresh = () => startTransition(() => void router.invalidate());
  const handle = (result: Awaited<ReturnType<typeof createTask>>, message: string) => { if (result._tag === "invalid") { setErrors(result.fields); return false; } if (result._tag === "conflict") { setErrors([{ field: "form", message: result.reason === "has_dependents" ? "This assessment has linked tasks and cannot be deleted." : "This record changed elsewhere. Reload before trying again." }]); return false; } if (result._tag !== "applied" && result._tag !== "already_applied") { setErrors([{ field: "form", message: result._tag === "not_found" ? "This record is no longer available." : "The change could not be saved. Retry when ready." }]); return false; } setNotice({ message, token: result.undoToken }); refresh(); return true; };
  const create = async (values: AcademicFormValues) => { setPending(true); setErrors([]); try { const result = createKind === "task" ? await createTask({ data: values }) : await createAssessment({ data: { title: values.title, details: values.details, courseId: values.courseId, dueDate: values.dueDate, dueTime: values.dueTime, idempotencyKey: values.idempotencyKey } }); if (handle(result, `${createKind === "task" ? "Task" : "Assessment"} created.`)) setCreateOpen(false); } finally { setPending(false); } };
  const openAssessment = async (id: string) => { setErrors([]); const value = await getAssessment({ data: id }); if (value && !Array.isArray(value) && "status" in value && !("assessmentId" in value)) setSelected(value); else setNotice({ message: "This assessment is no longer available. Reloading deadlines." }); };
  const update = async (values: AcademicFormValues) => { if (!selected) return; setPending(true); setErrors([]); try { const { idempotencyKey, ...patch } = values; if (handle(await updateAssessment({ data: { assessmentId: selected.id, expectedVersion: selected.version, patch, idempotencyKey } }), "Assessment updated.")) setSelected(undefined); } finally { setPending(false); } };
  const status = async (row: Deadline, next: AcademicStatus) => { const previous = rows; setRows((current) => current.map((item) => item.id === row.id && item.kind === row.kind ? { ...item, status: next, version: item.version + 1 } : item)); setPending(true); setErrors([]); try { const input = { id: row.id, expectedVersion: row.version, status: next, idempotencyKey: crypto.randomUUID() }; const result = row.kind === "task" ? await setTaskStatus({ data: input }) : await setAssessmentStatus({ data: input }); if (!handle(result, next === "open" ? `${label(row)} reopened.` : next === "completed" ? `${label(row)} completed.` : `${label(row)} cancelled.`)) setRows(previous); } catch (error) { setRows(previous); throw error; } finally { setPending(false); } };
  const remove = async () => { if (!deleteRow) return; setPending(true); setErrors([]); try { const input = { id: deleteRow.id, expectedVersion: deleteRow.version, idempotencyKey: crypto.randomUUID() }; const result = deleteRow.kind === "task" ? await deleteTask({ data: input }) : await deleteAssessment({ data: input }); if (handle(result, `${label(deleteRow)} deleted.`)) setDeleteRow(undefined); } finally { setPending(false); } };
  const undo = async () => { if (!notice?.token) return; const result = await undoAcademicCommand({ data: { token: notice.token, idempotencyKey: crypto.randomUUID() } }); setNotice({ message: result._tag === "applied" ? "Change undone." : "This change can no longer be undone. Reload to see current data." }); if (result._tag === "applied") refresh(); };
  const submitSearch = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const q = String(new FormData(event.currentTarget).get("q") ?? "").trim(); void navigate({ search: (previous) => ({ ...previous, q: q || undefined, cursor: undefined }), replace: true }); };
  const setFilter = (next: Record<string, string | boolean | undefined>) => { const value = { ...filters, ...next, cursor: undefined }; setFilters(value); void navigate({ search: value, replace: true }); };
  const visibleRows = rows.filter((row) => (!filters.kind || filters.kind === "all" || row.kind === filters.kind) && (!filters.status || filters.status === "all" || row.status === filters.status) && (!filters.courseId || row.courseId === filters.courseId));
  const overdue = visibleRows.filter((row) => row.status === "open" && row.dueDate < from);
  const upcoming = visibleRows.filter((row) => !(row.status === "open" && row.dueDate < from));
  const grouped = new Map<string, Array<Deadline>>();
  for (const row of upcoming) grouped.set(row.dueDate, [...(grouped.get(row.dueDate) ?? []), row]);
  const openCount = visibleRows.filter((row) => row.status === "open").length;
  const assessmentCount = visibleRows.filter((row) => row.kind === "assessment").length;
  const filtered = Boolean(filters.q || filters.kind !== "all" || filters.status !== "open" || filters.courseId || filters.from || filters.to || filters.includeOverdue === false);

  return <AcademicShell><div className="min-h-full bg-kumo-canvas text-base text-kumo-default"><main className="mx-auto w-full max-w-6xl px-4 py-8 pb-24 sm:px-7 lg:px-10 lg:py-12">
    <header className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end">
      <div className="max-w-2xl"><div className="mb-4 flex items-center gap-2 text-base font-medium text-kumo-brand"><CalendarCheck aria-hidden="true" size={20} weight="duotone" /><span>Academic timeline</span></div><h1 className="text-4xl font-semibold leading-none text-kumo-strong sm:text-5xl">Deadlines</h1><p className="mt-4 text-lg text-kumo-subtle"><span className="font-medium text-kumo-default">{formatRange(from, to)}</span><span aria-hidden="true" className="mx-2">·</span>{timeZone}</p></div>
      <Dialog.Root open={createOpen} onOpenChange={setCreateOpen}><Dialog.Trigger render={(props) => <Button {...props} icon={<Plus aria-hidden="true" size={18} weight="bold" />} className="min-h-11 px-5 text-base shadow-sm transition-transform duration-150 ease-out motion-reduce:transition-none active:scale-[0.96] motion-reduce:active:scale-100">Add work</Button>} /><Dialog className="max-h-[calc(100svh-1rem)] overflow-y-auto p-5 sm:max-w-2xl sm:p-6"><div className="mb-5 flex items-center justify-between"><Dialog.Title className="text-xl font-semibold">Create academic work</Dialog.Title><Dialog.Close aria-label="Close create form" render={(props) => <Button {...props} title="Close create form" variant="secondary" shape="square" className="min-h-11 min-w-11" icon={<X aria-hidden="true" size={18} />} />} /></div><fieldset className="mb-5 grid grid-cols-2 gap-2"><legend className="sr-only">Record type</legend>{(["task", "assessment"] as const).map((kind) => <button key={kind} type="button" aria-pressed={createKind === kind} onClick={() => setCreateKind(kind)} className={`min-h-11 rounded-lg px-3 text-base font-medium ring ring-kumo-line focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-kumo-focus ${createKind === kind ? "bg-kumo-strong text-kumo-inverse" : "bg-kumo-base hover:bg-kumo-tint"}`}>{kind === "task" ? "Task" : "Assessment"}</button>)}</fieldset><AcademicForm key={createKind} kind={createKind} courses={courses} assessments={assessments} errors={errors} pending={pending} onCancel={() => setCreateOpen(false)} onSubmit={create} /></Dialog></Dialog.Root>
    </header>

    <section aria-label="Deadline summary" className="mt-10 grid overflow-hidden rounded-2xl bg-kumo-base shadow-sm ring ring-kumo-line sm:grid-cols-3">
      <SummaryMetric value={openCount} label="Open" />
      <SummaryMetric value={overdue.length} label="Overdue" urgent={overdue.length > 0} />
      <SummaryMetric value={assessmentCount} label="Assessments" />
    </section>

    <section aria-label="Deadline filters" className="mt-5 rounded-2xl bg-kumo-base p-3 shadow-xs ring ring-kumo-line sm:p-4">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-center"><form onSubmit={submitSearch} className="flex min-w-0 flex-1 gap-2"><label htmlFor="deadline-search" className="sr-only">Search deadlines</label><div className="relative min-w-0 flex-1"><MagnifyingGlass aria-hidden="true" size={19} className="pointer-events-none absolute top-1/2 left-3.5 z-10 -translate-y-1/2 text-kumo-subtle" /><Input id="deadline-search" name="q" type="search" defaultValue={search.q ?? ""} placeholder="Search deadlines" className="min-h-11 pl-11 text-base" /></div><Button type="submit" variant="secondary" className="min-h-11 text-base">Search</Button></form><div className="hidden h-7 w-px bg-kumo-line lg:block" /><div className="flex items-center gap-2 text-base text-kumo-subtle"><FunnelSimple aria-hidden="true" size={18} /><span>{filtered ? "Filtered view" : "Default view"}</span></div></div>
      <div className="mt-4 grid gap-3 border-t border-kumo-line pt-4 sm:grid-cols-2 lg:grid-cols-4"><Select label="Type" value={search.kind ?? "all"} onChange={(value) => setFilter({ kind: value })} options={[["all", "All types"], ["task", "Tasks"], ["assessment", "Assessments"]]} /><Select label="Status" value={search.status ?? "open"} onChange={(value) => setFilter({ status: value })} options={[["open", "Open"], ["completed", "Completed"], ["cancelled", "Cancelled"], ["all", "All statuses"]]} /><Select label="Course" value={search.courseId ?? ""} onChange={(value) => setFilter({ courseId: value || undefined })} options={[["", "All courses"], ...courses.map((course) => [course.id, course.title] as const)]} /><Select label="Results" value={String(search.pageSize ?? 25)} onChange={(value) => setFilter({ pageSize: value })} options={[["10", "10 per page"], ["25", "25 per page"], ["50", "50 per page"], ["100", "100 per page"]]} /></div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_auto]"><label className="grid gap-1.5 font-medium">From<Input className="min-h-11 text-base" type="date" value={from} onChange={(event) => setFilter({ from: event.target.value })} /></label><label className="grid gap-1.5 font-medium">To<Input className="min-h-11 text-base" type="date" value={to} onChange={(event) => setFilter({ to: event.target.value })} /></label><label className="flex min-h-11 items-center gap-3 self-end rounded-lg bg-kumo-canvas px-4 font-medium ring ring-kumo-line"><input className="size-4 accent-current" type="checkbox" checked={search.includeOverdue ?? true} onChange={(event) => setFilter({ includeOverdue: event.target.checked })} />Include overdue</label></div>
    </section>

    <div className="mt-10 flex items-end justify-between gap-4"><div><h2 className="text-xl font-semibold text-kumo-strong">Your timeline</h2><p role="status" className="mt-1 text-base text-kumo-subtle">{page.items.length} {page.items.length === 1 ? "deadline" : "deadlines"}{page.hasNext ? " on this page" : ""}</p></div>{filtered ? <button type="button" onClick={() => void navigate({ search: {} })} className="min-h-11 rounded-lg px-3 font-medium text-kumo-brand hover:bg-kumo-tint focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-kumo-focus">Clear filters</button> : null}</div>
    {page.invalidCursor ? <p role="status" className="mt-3 rounded-lg bg-kumo-warning-tint px-4 py-3 text-kumo-warning">That page link expired. Showing the first page.</p> : null}
    {page.items.length === 0 ? <LayerCard className="mt-5 rounded-2xl px-6 py-14 text-center shadow-sm ring ring-kumo-line"><span className="mx-auto flex size-14 items-center justify-center rounded-2xl bg-kumo-tint text-kumo-subtle"><CalendarCheck aria-hidden="true" size={28} weight="duotone" /></span><h2 className="mt-5 text-xl font-semibold text-kumo-strong">No deadlines match this view</h2><div className="mt-6 flex flex-wrap justify-center gap-3"><Button className="min-h-11 text-base" variant="secondary" onClick={() => void navigate({ search: {} })}>Clear filters</Button><Button className="min-h-11 text-base" onClick={() => setCreateOpen(true)}>Add work</Button></div></LayerCard> : <div className="mt-6 grid gap-10">{overdue.length > 0 ? <DeadlineGroup heading="Overdue" rows={overdue} pending={pending} onEdit={openAssessment} onStatus={status} onDelete={setDeleteRow} /> : null}{[...grouped].map(([date, rows]) => <DeadlineGroup key={date} heading={formatLongDay(date)} date={date} rows={rows} pending={pending} onEdit={openAssessment} onStatus={status} onDelete={setDeleteRow} />)}</div>}
    {page.hasNext && page.nextCursor ? <div className="mt-8 flex justify-end"><Button className="min-h-11 text-base" variant="secondary" onClick={() => void navigate({ search: (previous) => ({ ...previous, cursor: page.nextCursor ?? undefined }) })}>Next page</Button></div> : null}
    <Dialog.Root open={Boolean(selected)} onOpenChange={(open) => { if (!open) setSelected(undefined); }}><Dialog className="max-h-[calc(100svh-1rem)] overflow-y-auto p-5 sm:max-w-2xl sm:p-6"><div className="mb-5 flex items-center justify-between"><Dialog.Title className="text-xl font-semibold">Edit assessment</Dialog.Title><Dialog.Close aria-label="Close edit assessment" render={(props) => <Button {...props} title="Close edit assessment" variant="secondary" shape="square" className="min-h-11 min-w-11" icon={<X aria-hidden="true" size={18} />} />} /></div>{selected ? <AcademicForm kind="assessment" record={selected} courses={courses} errors={errors} pending={pending} onCancel={() => setSelected(undefined)} onSubmit={update} /> : null}</Dialog></Dialog.Root>
    <Dialog.Root open={Boolean(deleteRow)} onOpenChange={(open) => { if (!open) setDeleteRow(undefined); }}><Dialog className="p-5 sm:max-w-md sm:p-6"><WarningCircle aria-hidden="true" size={24} className="text-kumo-danger" /><Dialog.Title className="mt-3 text-xl font-semibold">Delete {deleteRow?.title ?? "record"}?</Dialog.Title><Dialog.Description className="mt-2 text-base text-kumo-subtle">It will be removed from Deadlines and Canvas.</Dialog.Description>{errors.length > 0 ? <p role="alert" className="mt-3 text-base text-kumo-danger">{errors[0]?.message}</p> : null}<div className="mt-6 flex justify-end gap-2"><Button className="min-h-11 text-base" variant="secondary" onClick={() => setDeleteRow(undefined)}>Cancel</Button><Button className="min-h-11 text-base" disabled={pending} icon={<Trash aria-hidden="true" size={16} />} onClick={() => void remove()}>Delete</Button></div></Dialog></Dialog.Root>
  </main></div>{notice ? <AcademicToast message={notice.message} undoToken={notice.token} pending={pending} onUndo={() => void undo()} /> : null}</AcademicShell>;
}

function SummaryMetric({ value, label, urgent = false }: { readonly value: number; readonly label: string; readonly urgent?: boolean }) { return <div className="flex items-baseline justify-between gap-4 border-kumo-line px-5 py-4 sm:block sm:border-s sm:first:border-s-0 sm:px-6 sm:py-5"><p className={`text-3xl font-semibold tabular-nums ${urgent ? "text-kumo-danger" : "text-kumo-strong"}`}>{value}</p><p className="mt-1 text-base text-kumo-subtle">{label}</p></div>; }
function DeadlineGroup({ heading, date, rows, pending, onEdit, onStatus, onDelete }: { readonly heading: string; readonly date?: string; readonly rows: ReadonlyArray<Deadline>; readonly pending: boolean; readonly onEdit: (id: string) => void; readonly onStatus: (row: Deadline, status: AcademicStatus) => void; readonly onDelete: (row: Deadline) => void }) { const overdue = date === undefined; return <section aria-labelledby={`deadline-${date ?? "overdue"}`} className="grid gap-4 lg:grid-cols-[11rem_minmax(0,1fr)] lg:gap-8"><div><h3 id={`deadline-${date ?? "overdue"}`} className={`text-lg font-semibold ${overdue ? "text-kumo-danger" : "text-kumo-strong"}`}>{heading}</h3><p className="mt-1 text-base text-kumo-subtle">{rows.length} {rows.length === 1 ? "item" : "items"}</p></div><LayerCard className="overflow-hidden rounded-2xl shadow-sm ring ring-kumo-line"><ol className="divide-y divide-kumo-line">{rows.map((row) => <DeadlineRow key={`${row.kind}-${row.id}`} row={row} overdue={overdue} pending={pending} onEdit={onEdit} onStatus={onStatus} onDelete={onDelete} />)}</ol></LayerCard></section>; }
function DeadlineRow({ row, overdue, pending, onEdit, onStatus, onDelete }: { readonly row: Deadline; readonly overdue: boolean; readonly pending: boolean; readonly onEdit: (id: string) => void; readonly onStatus: (row: Deadline, status: AcademicStatus) => void; readonly onDelete: (row: Deadline) => void }) { const titleClass = "inline-flex min-h-11 items-center text-left text-lg font-medium text-kumo-strong underline-offset-4 hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-kumo-focus"; return <li className="group grid gap-4 px-4 py-5 sm:px-6 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center"><div className="flex min-w-0 items-start gap-4"><span aria-hidden="true" className={`mt-2.5 size-2.5 shrink-0 rounded-full ring-4 ${overdue ? "bg-kumo-danger ring-kumo-danger-tint" : row.status === "completed" ? "bg-kumo-success ring-kumo-success-tint" : "bg-kumo-brand ring-kumo-brand-tint"}`} /><div className="min-w-0"><div className="flex flex-wrap items-center gap-x-3 gap-y-1">{row.kind === "task" ? <Link to="/tasks/$taskId" params={{ taskId: row.id }} className={titleClass}>{row.title}</Link> : <button type="button" onClick={() => void onEdit(row.id)} className={titleClass}>{row.title}</button>}<Badge variant="secondary">{row.kind === "task" ? "Task" : "Assessment"}</Badge>{overdue ? <Badge variant="error">Overdue</Badge> : row.status !== "open" ? <Badge variant="secondary">{row.status === "completed" ? "Completed" : "Cancelled"}</Badge> : null}</div><div className="mt-1 flex flex-wrap items-center gap-x-4 gap-y-1 text-base text-kumo-subtle">{row.courseTitle ? <span className="font-medium text-kumo-default">{row.courseTitle}</span> : <span>No course</span>}<span className="flex items-center gap-1.5"><Clock aria-hidden="true" size={17} /><time dateTime={`${row.dueDate}${row.dueTime ? `T${row.dueTime}` : ""}`}>{row.dueTime ? formatTime(row.dueTime) : "No set time"}</time></span></div></div></div><div className="flex flex-wrap items-center gap-2 ps-6 sm:ps-7 lg:ps-0">{row.status === "open" ? <><Button className="min-h-11 text-base transition-transform duration-150 ease-out motion-reduce:transition-none active:scale-[0.96] motion-reduce:active:scale-100" variant="secondary" disabled={pending} icon={<Check aria-hidden="true" size={17} weight="bold" />} onClick={() => void onStatus(row, "completed")}>Complete</Button><Button className="min-h-11 text-base" variant="secondary" disabled={pending} onClick={() => void onStatus(row, "cancelled")}>Cancel</Button></> : <Button className="min-h-11 text-base" variant="secondary" disabled={pending} onClick={() => void onStatus(row, "open")}>Reopen</Button>}<Button className="min-h-11 min-w-11" variant="secondary" shape="square" aria-label={`Delete ${row.title}`} disabled={pending} icon={<Trash aria-hidden="true" size={18} />} onClick={() => onDelete(row)} /></div></li>; }
function Select({ label, value, options, onChange }: { readonly label: string; readonly value: string; readonly options: ReadonlyArray<readonly [string, string]>; readonly onChange: (value: string) => void }) { return <label className="grid gap-1.5 font-medium">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="min-h-11 rounded-lg bg-kumo-base px-3 text-base ring ring-kumo-line focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-kumo-focus">{options.map(([key, text]) => <option key={key || "all"} value={key}>{text}</option>)}</select></label>; }
function label(row: Deadline) { return row.kind === "task" ? "Task" : "Assessment"; }
function formatDay(value: string) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(`${value}T12:00:00Z`)); }
function formatLongDay(value: string) { return new Intl.DateTimeFormat("en", { weekday: "long", month: "long", day: "numeric", timeZone: "UTC" }).format(new Date(`${value}T12:00:00Z`)); }
function formatRange(from: string, to: string) { return `${formatDay(from)} - ${new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(`${to}T12:00:00Z`))}`; }
function formatTime(value: string) { const [hour = 0, minute = 0] = value.split(":").map(Number); return new Intl.DateTimeFormat("en", { hour: "numeric", minute: "2-digit", timeZone: "UTC" }).format(new Date(Date.UTC(2000, 0, 1, hour, minute))); }
function isCourseOptions(value: unknown): value is ReadonlyArray<CourseOption> { return Array.isArray(value) && value.every((item) => typeof item === "object" && item !== null && "id" in item && "title" in item && !("status" in item)); }
function isAssessmentOptions(value: unknown): value is ReadonlyArray<AssessmentOption> { return Array.isArray(value) && value.every((item) => typeof item === "object" && item !== null && "courseId" in item && !("status" in item)); }
