import { Badge } from "@cloudflare/kumo/components/badge";
import { Button } from "@cloudflare/kumo/components/button";
import { Dialog } from "@cloudflare/kumo/components/dialog";
import { Input } from "@cloudflare/kumo/components/input";
import { LayerCard } from "@cloudflare/kumo/components/layer-card";
import { CalendarCheck, MagnifyingGlass, Plus, Trash, WarningCircle, X } from "@phosphor-icons/react";
import { createFileRoute, Link, useRouter } from "@tanstack/react-router";
import { startTransition, useState } from "react";
import { z } from "zod";

import { AcademicError, AcademicLoading, AcademicToast } from "../components/academic/academic-feedback";
import { AcademicForm, type AcademicFormValues } from "../components/academic/academic-form";
import { AcademicShell } from "../components/academic/academic-shell";
import type { AcademicFieldError, AcademicStatus, Assessment, AssessmentOption, CourseOption, Deadline } from "../server/academic/domain";
import { createAssessment, createTask, deleteAssessment, deleteTask, getAcademicWorkloadRange, getAssessment, listAssessmentOptions, listCourseOptions, listDeadlines, setAssessmentStatus, setTaskStatus, undoAcademicCommand, updateAssessment } from "../server/academic/functions";
import { requireAuthenticatedRoute } from "../server/auth/functions";

const isoDate = /^\d{4}-\d{2}-\d{2}$/;
const searchSchema = z.object({ q: z.string().max(100).optional().catch(undefined), kind: z.enum(["all", "task", "assessment"]).optional().catch("all"), status: z.enum(["open", "completed", "cancelled", "all"]).optional().catch("open"), courseId: z.string().uuid().optional().catch(undefined), from: z.string().regex(isoDate).optional().catch(undefined), to: z.string().regex(isoDate).optional().catch(undefined), includeOverdue: z.union([z.boolean(), z.enum(["true", "false"])]).transform((value) => value === true || value === "true").optional().catch(true), pageSize: z.coerce.number().pipe(z.union([z.literal(10), z.literal(25), z.literal(50), z.literal(100)])).optional().catch(25), cursor: z.string().max(2048).optional().catch(undefined) });
const plusDays = (value: string, days: number) => { const date = new Date(`${value}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); };

export const Route = createFileRoute("/deadlines")({
  beforeLoad: requireAuthenticatedRoute,
  validateSearch: searchSchema,
  loaderDeps: ({ search }) => search,
  loader: async ({ deps }) => { const defaultRange = await getAcademicWorkloadRange(); const from = deps.from ?? defaultRange.from; const to = deps.to && deps.to >= from ? deps.to : deps.from ? plusDays(from, 6) : defaultRange.to; const [page, courseResult, assessmentResult] = await Promise.all([listDeadlines({ data: { q: deps.q?.trim() ?? "", kind: deps.kind ?? "all", status: deps.status ?? "open", courseId: deps.courseId ?? null, from, to, includeOverdue: deps.includeOverdue ?? true, pageSize: deps.pageSize ?? 25, cursor: deps.cursor ?? null } }), listCourseOptions(), listAssessmentOptions()]); return { page, courses: isCourseOptions(courseResult) ? courseResult : [], assessments: isAssessmentOptions(assessmentResult) ? assessmentResult : [], from, to, timeZone: defaultRange.timeZone }; },
  pendingComponent: () => <AcademicLoading title="Deadlines" />,
  errorComponent: ({ reset }) => <AcademicError title="Deadlines unavailable" reset={reset} />,
  component: DeadlinesRoute,
});

function DeadlinesRoute() {
  const { page, courses, assessments, from, to, timeZone } = Route.useLoaderData(); const search = Route.useSearch(); const navigate = Route.useNavigate(); const router = useRouter();
  const [createOpen, setCreateOpen] = useState(false); const [createKind, setCreateKind] = useState<"task" | "assessment">("task"); const [selected, setSelected] = useState<Assessment>(); const [deleteRow, setDeleteRow] = useState<Deadline>(); const [pending, setPending] = useState(false); const [errors, setErrors] = useState<ReadonlyArray<AcademicFieldError>>([]); const [notice, setNotice] = useState<{ readonly message: string; readonly token?: string }>();
  const refresh = () => startTransition(() => void router.invalidate());
  const handle = (result: Awaited<ReturnType<typeof createTask>>, message: string) => { if (result._tag === "invalid") { setErrors(result.fields); return false; } if (result._tag === "conflict") { setErrors([{ field: "form", message: result.reason === "has_dependents" ? "This assessment has linked tasks and cannot be deleted." : "This record changed elsewhere. Reload before trying again." }]); return false; } if (result._tag !== "applied" && result._tag !== "already_applied") { setErrors([{ field: "form", message: result._tag === "not_found" ? "This record is no longer available." : "The change could not be saved. Retry when ready." }]); return false; } setNotice({ message, token: result.undoToken }); refresh(); return true; };
  const create = async (values: AcademicFormValues) => { setPending(true); setErrors([]); try { const result = createKind === "task" ? await createTask({ data: values }) : await createAssessment({ data: { title: values.title, details: values.details, courseId: values.courseId, dueDate: values.dueDate, dueTime: values.dueTime, idempotencyKey: values.idempotencyKey } }); if (handle(result, `${createKind === "task" ? "Task" : "Assessment"} created.`)) setCreateOpen(false); } finally { setPending(false); } };
  const openAssessment = async (id: string) => { setErrors([]); const value = await getAssessment({ data: id }); if (value && !Array.isArray(value) && "status" in value && !("assessmentId" in value)) setSelected(value); else setNotice({ message: "This assessment is no longer available. Reloading deadlines." }); };
  const update = async (values: AcademicFormValues) => { if (!selected) return; setPending(true); setErrors([]); try { const { idempotencyKey, ...patch } = values; if (handle(await updateAssessment({ data: { assessmentId: selected.id, expectedVersion: selected.version, patch, idempotencyKey } }), "Assessment updated.")) setSelected(undefined); } finally { setPending(false); } };
  const status = async (row: Deadline, next: AcademicStatus) => { setPending(true); setErrors([]); try { const input = { id: row.id, expectedVersion: row.version, status: next, idempotencyKey: crypto.randomUUID() }; const result = row.kind === "task" ? await setTaskStatus({ data: input }) : await setAssessmentStatus({ data: input }); handle(result, next === "open" ? `${label(row)} reopened.` : next === "completed" ? `${label(row)} completed.` : `${label(row)} cancelled.`); } finally { setPending(false); } };
  const remove = async () => { if (!deleteRow) return; setPending(true); setErrors([]); try { const input = { id: deleteRow.id, expectedVersion: deleteRow.version, idempotencyKey: crypto.randomUUID() }; const result = deleteRow.kind === "task" ? await deleteTask({ data: input }) : await deleteAssessment({ data: input }); if (handle(result, `${label(deleteRow)} deleted.`)) setDeleteRow(undefined); } finally { setPending(false); } };
  const undo = async () => { if (!notice?.token) return; const result = await undoAcademicCommand({ data: { token: notice.token, idempotencyKey: crypto.randomUUID() } }); setNotice({ message: result._tag === "applied" ? "Change undone." : "This change can no longer be undone. Reload to see current data." }); if (result._tag === "applied") refresh(); };
  const submitSearch = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const q = String(new FormData(event.currentTarget).get("q") ?? "").trim(); void navigate({ search: (previous) => ({ ...previous, q: q || undefined, cursor: undefined }), replace: true }); };
  const setFilter = (next: Record<string, string | boolean | undefined>) => void navigate({ search: (previous) => ({ ...previous, ...next, cursor: undefined }) });
  const overdue = page.items.filter((row) => row.status === "open" && row.dueDate < from); const upcoming = page.items.filter((row) => !(row.status === "open" && row.dueDate < from)); const grouped = new Map<string, Array<Deadline>>(); for (const row of upcoming) grouped.set(row.dueDate, [...(grouped.get(row.dueDate) ?? []), row]);
  return <AcademicShell><main className="mx-auto w-full max-w-5xl px-4 py-6 pb-24 sm:px-6 md:py-8 lg:px-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold text-kumo-strong">Deadlines</h1><p className="mt-1 text-sm text-kumo-subtle">{formatDay(from)} - {formatDay(to)} · {timeZone}</p></div><Dialog.Root open={createOpen} onOpenChange={setCreateOpen}><Dialog.Trigger render={(props) => <Button {...props} icon={<Plus aria-hidden="true" size={16} />} className="min-h-11 transition-transform duration-150 ease-out active:scale-[0.96]">Create</Button>} /><Dialog className="max-h-[calc(100svh-1rem)] overflow-y-auto p-5 sm:max-w-2xl sm:p-6"><div className="mb-5 flex items-center justify-between"><Dialog.Title className="text-xl font-semibold">Create academic work</Dialog.Title><Dialog.Close aria-label="Close create form" render={(props) => <Button {...props} title="Close create form" variant="secondary" shape="square" icon={<X aria-hidden="true" size={18} />} />} /></div><fieldset className="mb-5 grid grid-cols-2 gap-2"><legend className="sr-only">Record type</legend>{(["task", "assessment"] as const).map((kind) => <button key={kind} type="button" aria-pressed={createKind === kind} onClick={() => setCreateKind(kind)} className={`min-h-11 rounded-lg px-3 text-sm font-medium ring ring-kumo-line ${createKind === kind ? "bg-kumo-strong text-kumo-inverse" : "hover:bg-kumo-tint"}`}>{kind === "task" ? "Task" : "Assessment"}</button>)}</fieldset><AcademicForm key={createKind} kind={createKind} courses={courses} assessments={assessments} errors={errors} pending={pending} onCancel={() => setCreateOpen(false)} onSubmit={create} /></Dialog></Dialog.Root></div>
    <div className="mt-6 grid gap-3"><form onSubmit={submitSearch} className="flex gap-2"><label htmlFor="deadline-search" className="sr-only">Search deadlines</label><Input id="deadline-search" name="q" type="search" defaultValue={search.q ?? ""} placeholder="Search deadlines" className="text-base sm:text-sm" /><Button type="submit" variant="secondary" shape="square" aria-label="Search deadlines" icon={<MagnifyingGlass aria-hidden="true" size={18} />} /></form><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-5"><Select label="Type" value={search.kind ?? "all"} onChange={(value) => setFilter({ kind: value })} options={[["all", "All types"], ["task", "Tasks"], ["assessment", "Assessments"]]} /><Select label="Status" value={search.status ?? "open"} onChange={(value) => setFilter({ status: value })} options={[["open", "Open"], ["completed", "Completed"], ["cancelled", "Cancelled"], ["all", "All statuses"]]} /><Select label="Course" value={search.courseId ?? ""} onChange={(value) => setFilter({ courseId: value || undefined })} options={[["", "All courses"], ...courses.map((course) => [course.id, course.title] as const)]} /><Select label="Page size" value={String(search.pageSize ?? 25)} onChange={(value) => setFilter({ pageSize: value })} options={[["10", "10"], ["25", "25"], ["50", "50"], ["100", "100"]]} /><label className="flex min-h-11 items-center gap-2 rounded-lg px-3 ring ring-kumo-line"><input type="checkbox" checked={search.includeOverdue ?? true} onChange={(event) => setFilter({ includeOverdue: event.target.checked })} />Include overdue</label></div><div className="grid gap-2 sm:grid-cols-2"><label className="grid gap-1 font-medium">From<Input type="date" value={from} onChange={(event) => setFilter({ from: event.target.value })} /></label><label className="grid gap-1 font-medium">To<Input type="date" value={to} onChange={(event) => setFilter({ to: event.target.value })} /></label></div></div>
    <p role="status" className="mt-5 text-sm text-kumo-subtle">{page.items.length} {page.items.length === 1 ? "deadline" : "deadlines"}{page.hasNext ? " on this page" : ""}</p>{page.invalidCursor ? <p role="status" className="mt-2 text-kumo-warning">That page link expired. Showing the first page.</p> : null}
    {page.items.length === 0 ? <LayerCard className="mt-5 px-6 py-10 text-center"><CalendarCheck aria-hidden="true" size={28} className="mx-auto text-kumo-subtle" /><h2 className="mt-3 text-lg font-semibold">No deadlines match this view</h2><div className="mt-5 flex justify-center gap-2"><Button variant="secondary" onClick={() => void navigate({ search: {} })}>Clear filters</Button><Button onClick={() => setCreateOpen(true)}>Create</Button></div></LayerCard> : <div className="mt-6 grid gap-7">{overdue.length > 0 ? <DeadlineGroup heading="Overdue" rows={overdue} pending={pending} onEdit={openAssessment} onStatus={status} onDelete={setDeleteRow} /> : null}{[...grouped].map(([date, rows]) => <DeadlineGroup key={date} heading={formatLongDay(date)} date={date} rows={rows} pending={pending} onEdit={openAssessment} onStatus={status} onDelete={setDeleteRow} />)}</div>}
    {page.hasNext && page.nextCursor ? <div className="mt-5 flex justify-end"><Button variant="secondary" onClick={() => void navigate({ search: (previous) => ({ ...previous, cursor: page.nextCursor ?? undefined }) })}>Next page</Button></div> : null}
    <Dialog.Root open={Boolean(selected)} onOpenChange={(open) => { if (!open) setSelected(undefined); }}><Dialog className="max-h-[calc(100svh-1rem)] overflow-y-auto p-5 sm:max-w-2xl sm:p-6"><div className="mb-5 flex items-center justify-between"><Dialog.Title className="text-xl font-semibold">Edit assessment</Dialog.Title><Dialog.Close aria-label="Close edit assessment" render={(props) => <Button {...props} title="Close edit assessment" variant="secondary" shape="square" icon={<X aria-hidden="true" size={18} />} />} /></div>{selected ? <AcademicForm kind="assessment" record={selected} courses={courses} errors={errors} pending={pending} onCancel={() => setSelected(undefined)} onSubmit={update} /> : null}</Dialog></Dialog.Root>
    <Dialog.Root open={Boolean(deleteRow)} onOpenChange={(open) => { if (!open) setDeleteRow(undefined); }}><Dialog className="p-5 sm:max-w-md sm:p-6"><WarningCircle aria-hidden="true" size={24} className="text-kumo-danger" /><Dialog.Title className="mt-3 text-xl font-semibold">Delete {deleteRow?.title ?? "record"}?</Dialog.Title><Dialog.Description className="mt-2 text-sm text-kumo-subtle">It will be removed from Deadlines and Canvas.</Dialog.Description>{errors.length > 0 ? <p role="alert" className="mt-3 text-sm text-kumo-danger">{errors[0]?.message}</p> : null}<div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={() => setDeleteRow(undefined)}>Cancel</Button><Button disabled={pending} icon={<Trash aria-hidden="true" size={16} />} onClick={() => void remove()}>Delete</Button></div></Dialog></Dialog.Root>
  </main>{notice ? <AcademicToast message={notice.message} undoToken={notice.token} pending={pending} onUndo={() => void undo()} /> : null}</AcademicShell>;
}

function DeadlineGroup({ heading, date, rows, pending, onEdit, onStatus, onDelete }: { readonly heading: string; readonly date?: string; readonly rows: ReadonlyArray<Deadline>; readonly pending: boolean; readonly onEdit: (id: string) => void; readonly onStatus: (row: Deadline, status: AcademicStatus) => void; readonly onDelete: (row: Deadline) => void }) { return <section aria-labelledby={`deadline-${date ?? "overdue"}`}><h2 id={`deadline-${date ?? "overdue"}`} className="mb-3 text-base font-semibold">{heading}</h2><LayerCard><ol className="divide-y divide-kumo-line">{rows.map((row) => <li key={`${row.kind}-${row.id}`} className="grid gap-3 px-4 py-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center sm:px-5"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2">{row.kind === "task" ? <Link to="/tasks/$taskId" params={{ taskId: row.id }} className="font-medium text-kumo-strong underline-offset-4 hover:underline">{row.title}</Link> : <button type="button" onClick={() => void onEdit(row.id)} className="min-h-11 text-left font-medium text-kumo-strong underline-offset-4 hover:underline">{row.title}</button>}<Badge variant="secondary">{row.kind}</Badge></div><div className="mt-1 flex flex-wrap gap-2 text-xs text-kumo-subtle">{row.courseTitle ? <span>{row.courseTitle}</span> : null}<time dateTime={`${row.dueDate}${row.dueTime ? `T${row.dueTime}` : ""}`}>{row.dueTime ?? "No time"}</time><span>{row.status}</span></div></div><div className="flex flex-wrap gap-2">{row.status === "open" ? <><Button variant="secondary" disabled={pending} onClick={() => void onStatus(row, "completed")}>Complete</Button><Button variant="secondary" disabled={pending} onClick={() => void onStatus(row, "cancelled")}>Cancel</Button></> : <Button variant="secondary" disabled={pending} onClick={() => void onStatus(row, "open")}>Reopen</Button>}<Button variant="secondary" disabled={pending} onClick={() => onDelete(row)}>Delete</Button></div></li>)}</ol></LayerCard></section>; }
function Select({ label, value, options, onChange }: { readonly label: string; readonly value: string; readonly options: ReadonlyArray<readonly [string, string]>; readonly onChange: (value: string) => void }) { return <label className="grid gap-1 font-medium">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="min-h-11 rounded-lg bg-kumo-base px-3 text-base ring ring-kumo-line sm:text-sm">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function label(row: Deadline) { return row.kind === "task" ? "Task" : "Assessment"; }
function formatDay(value: string) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(`${value}T12:00:00Z`)); }
function formatLongDay(value: string) { return new Intl.DateTimeFormat("en", { weekday: "long", month: "long", day: "numeric", timeZone: "UTC" }).format(new Date(`${value}T12:00:00Z`)); }
function isCourseOptions(value: unknown): value is ReadonlyArray<CourseOption> { return Array.isArray(value) && value.every((item) => typeof item === "object" && item !== null && "id" in item && "title" in item && !("status" in item)); }
function isAssessmentOptions(value: unknown): value is ReadonlyArray<AssessmentOption> { return Array.isArray(value) && value.every((item) => typeof item === "object" && item !== null && "courseId" in item && !("status" in item)); }
