import { Badge } from "@cloudflare/kumo/components/badge";
import { Button } from "@cloudflare/kumo/components/button";
import { Dialog } from "@cloudflare/kumo/components/dialog";
import { LayerCard } from "@cloudflare/kumo/components/layer-card";
import { ArrowLeft, Trash, WarningCircle, X } from "@phosphor-icons/react";
import { createFileRoute, Link, notFound, useRouter } from "@tanstack/react-router";
import { startTransition, useEffect, useState } from "react";

import { AcademicToast } from "../components/academic/academic-feedback";
import { AcademicForm, type AcademicFormValues } from "../components/academic/academic-form";
import { AcademicShell } from "../components/academic/academic-shell";
import type { AcademicFieldError, AcademicStatus, AssessmentOption, CourseOption, Task } from "../server/academic/domain";
import { deleteTask, getTask, listAssessmentOptions, listCourseOptions, setTaskStatus, undoAcademicCommand, updateTask } from "../server/academic/functions";
import { requireAuthenticatedRoute } from "../server/auth/functions";

export const Route = createFileRoute("/tasks_/$taskId")({ beforeLoad: requireAuthenticatedRoute, loader: async ({ params }) => { const [task, courseResult, assessmentResult] = await Promise.all([getTask({ data: params.taskId }), listCourseOptions(), listAssessmentOptions()]); if (!isTask(task)) throw notFound(); return { task, courses: isCourseOptions(courseResult) ? courseResult : [], assessments: isAssessmentOptions(assessmentResult) ? assessmentResult : [] }; }, component: TaskDetailRoute, errorComponent: ({ reset }) => <AcademicShell><main className="mx-auto max-w-3xl px-4 py-12"><h1 className="text-2xl font-semibold">Task unavailable</h1><Button className="mt-5" onClick={reset}>Retry</Button></main></AcademicShell>, notFoundComponent: () => <AcademicShell><main className="mx-auto max-w-3xl px-4 py-12"><h1 className="text-2xl font-semibold">Task not found</h1><Link to="/tasks" className="mt-5 inline-flex min-h-11 items-center text-sm font-medium text-kumo-brand">Back to tasks</Link></main></AcademicShell> });

function TaskDetailRoute() {
  const { task, courses, assessments } = Route.useLoaderData(); const navigate = Route.useNavigate(); const router = useRouter();
  const [editOpen, setEditOpen] = useState(false); const [deleteOpen, setDeleteOpen] = useState(false); const [pending, setPending] = useState(false); const [errors, setErrors] = useState<ReadonlyArray<AcademicFieldError>>([]); const [notice, setNotice] = useState<{ readonly message: string; readonly token?: string }>();
  useEffect(() => { const stored = sessionStorage.getItem("kairo.academic.notice"); if (!stored) return; sessionStorage.removeItem("kairo.academic.notice"); try { const value: unknown = JSON.parse(stored); if (value && typeof value === "object" && "message" in value && typeof value.message === "string") { const token = Reflect.get(value, "token"); setNotice({ message: value.message, ...(typeof token === "string" ? { token } : {}) }); } } catch { /* Ignore stale route feedback. */ } }, []);
  const refresh = () => startTransition(() => void router.invalidate());
  const update = async (values: AcademicFormValues) => { setPending(true); setErrors([]); try { const { idempotencyKey, ...patch } = values; const result = await updateTask({ data: { taskId: task.id, expectedVersion: task.version, patch, idempotencyKey } }); if (result._tag === "invalid") setErrors(result.fields); else if (result._tag === "conflict") setErrors([{ field: "form", message: "This task changed elsewhere. Reload for current values; your edits remain here." }]); else if (result._tag === "applied" || result._tag === "already_applied") { setEditOpen(false); setNotice({ message: "Task updated.", token: result.undoToken }); refresh(); } else setErrors([{ field: "form", message: "The task could not be saved." }]); } finally { setPending(false); } };
  const status = async (next: AcademicStatus) => { setPending(true); try { const result = await setTaskStatus({ data: { id: task.id, expectedVersion: task.version, status: next, idempotencyKey: crypto.randomUUID() } }); if (result._tag === "applied" || result._tag === "already_applied") { setNotice({ message: next === "open" ? "Task reopened." : next === "completed" ? "Task completed." : "Task cancelled.", token: result.undoToken }); refresh(); } else setNotice({ message: result._tag === "conflict" ? "This task changed. Reload before trying again." : "The status could not be changed." }); } finally { setPending(false); } };
  const remove = async () => { setPending(true); try { const result = await deleteTask({ data: { id: task.id, expectedVersion: task.version, idempotencyKey: crypto.randomUUID() } }); if (result._tag === "applied" || result._tag === "already_applied") { sessionStorage.setItem("kairo.academic.notice", JSON.stringify({ message: "Task deleted.", token: result.undoToken })); await navigate({ to: "/tasks" }); } else setNotice({ message: "The task could not be deleted. Reload and try again." }); } finally { setPending(false); } };
  const undo = async () => { if (!notice?.token) return; const result = await undoAcademicCommand({ data: { token: notice.token, idempotencyKey: crypto.randomUUID() } }); setNotice({ message: result._tag === "applied" ? "Change undone." : "This change can no longer be undone. Reload to see current data." }); if (result._tag === "applied") refresh(); };
  const overdue = task.status === "open" && task.dueDate !== null && task.dueDate < new Date().toISOString().slice(0, 10);
  return <AcademicShell><main className="mx-auto max-w-4xl px-4 py-6 pb-24 sm:px-6 md:py-8 lg:px-10"><Link to="/tasks" className="inline-flex min-h-11 items-center gap-2 text-sm font-medium text-kumo-brand"><ArrowLeft aria-hidden="true" size={16} />Back to tasks</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold text-kumo-strong">{task.title}</h1><Badge variant="secondary">{task.status}</Badge>{overdue ? <Badge variant="error">Overdue</Badge> : null}</div>{task.courseTitle ? <p className="mt-1 text-sm text-kumo-subtle">{task.courseTitle}</p> : null}</div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => setEditOpen(true)}>Edit</Button>{task.status === "open" ? <><Button disabled={pending} onClick={() => void status("completed")}>Complete</Button><Button variant="secondary" disabled={pending} onClick={() => void status("cancelled")}>Cancel task</Button></> : <Button disabled={pending} onClick={() => void status("open")}>Reopen</Button>}<Button variant="secondary" icon={<Trash aria-hidden="true" size={16} />} onClick={() => setDeleteOpen(true)}>Delete</Button></div></div><div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1fr)_18rem]"><LayerCard className="px-5 py-5"><h2 className="text-base font-semibold">Task details</h2><dl className="mt-4 grid gap-4 text-sm">{task.details ? <div><dt className="text-kumo-subtle">Details</dt><dd className="mt-1 whitespace-pre-wrap">{task.details}</dd></div> : null}<div><dt className="text-kumo-subtle">Due</dt><dd className="mt-1 font-medium">{task.dueDate ?? "No due date"}{task.dueTime ? ` at ${task.dueTime}` : ""}</dd></div>{task.assessmentTitle ? <div><dt className="text-kumo-subtle">Assessment</dt><dd className="mt-1">{task.assessmentTitle}</dd></div> : null}</dl></LayerCard><section><h2 className="text-base font-semibold">Related</h2><div className="mt-3 grid gap-2">{task.courseId ? <Link to="/courses/$courseId" params={{ courseId: task.courseId }} className="flex min-h-11 items-center rounded-lg px-3 font-medium ring ring-kumo-line hover:bg-kumo-tint">Open course</Link> : null}{task.dueDate ? <Link to="/deadlines" search={{ from: task.dueDate, to: task.dueDate }} className="flex min-h-11 items-center rounded-lg px-3 font-medium ring ring-kumo-line hover:bg-kumo-tint">Open deadline</Link> : null}</div></section></div>
    <Dialog.Root open={editOpen} onOpenChange={setEditOpen}><Dialog className="max-h-[calc(100svh-1rem)] overflow-y-auto p-5 sm:max-w-2xl sm:p-6"><div className="mb-5 flex items-center justify-between"><Dialog.Title className="text-xl font-semibold">Edit task</Dialog.Title><Dialog.Close aria-label="Close edit task" render={(props) => <Button {...props} title="Close edit task" variant="secondary" shape="square" icon={<X aria-hidden="true" size={18} />} />} /></div><AcademicForm kind="task" record={task} courses={courses} assessments={assessments} errors={errors} pending={pending} onCancel={() => setEditOpen(false)} onSubmit={update} /></Dialog></Dialog.Root>
    <Dialog.Root open={deleteOpen} onOpenChange={setDeleteOpen}><Dialog className="p-5 sm:max-w-md sm:p-6"><WarningCircle aria-hidden="true" size={24} className="text-kumo-danger" /><Dialog.Title className="mt-3 text-xl font-semibold">Delete {task.title}?</Dialog.Title><Dialog.Description className="mt-2 text-sm text-kumo-subtle">The task will be removed from Tasks, Deadlines, and Canvas.</Dialog.Description><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={() => setDeleteOpen(false)}>Cancel</Button><Button disabled={pending} onClick={() => void remove()}>Delete task</Button></div></Dialog></Dialog.Root></main>{notice ? <AcademicToast message={notice.message} undoToken={notice.token} pending={pending} onUndo={() => void undo()} /> : null}</AcademicShell>;
}

function isTask(value: unknown): value is Task { return typeof value === "object" && value !== null && "assessmentId" in value && "status" in value; }
function isCourseOptions(value: unknown): value is ReadonlyArray<CourseOption> { return Array.isArray(value) && value.every((item) => typeof item === "object" && item !== null && "id" in item && "title" in item && !("status" in item)); }
function isAssessmentOptions(value: unknown): value is ReadonlyArray<AssessmentOption> { return Array.isArray(value) && value.every((item) => typeof item === "object" && item !== null && "courseId" in item && !("status" in item)); }
