import {
  boolean,
  date,
  foreignKey,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  time,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import { isNull, sql } from "drizzle-orm";

const id = () => uuid("id").defaultRandom().primaryKey();
const instant = (name: string) => timestamp(name, { withTimezone: true, mode: "date" }).notNull().defaultNow();
const optionalInstant = (name: string) => timestamp(name, { withTimezone: true, mode: "date" });

export const academicStatus = pgEnum("academic_status", ["open", "completed", "cancelled"]);
export const timetableKind = pgEnum("timetable_kind", ["one_off", "weekly"]);
export const canvasState = pgEnum("canvas_state", ["active", "archived"]);
export const fileKind = pgEnum("file_kind", ["markdown", "pdf"]);
export const fileLifecycleState = pgEnum("file_lifecycle_state", ["pending_upload", "processing", "ready", "failed", "rejected", "deleting"]);
export const fileExtractionState = pgEnum("file_extraction_state", ["pending", "ready", "truncated", "empty", "failed"]);
export const commandState = pgEnum("command_state", ["applied", "already_applied", "conflict", "not_found", "invalid", "unavailable"]);
export const notificationKind = pgEnum("notification_kind", ["deadline", "timetable", "focus_completion"]);
export const notificationChannel = pgEnum("notification_channel", ["in_app", "browser"]);
export const notificationEventState = pgEnum("notification_event_state", ["pending", "cancelled", "expired"]);
export const deliveryState = pgEnum("delivery_state", ["pending", "leased", "shown", "accepted", "clicked", "closed", "retrying", "failed", "expired"]);
export const focusState = pgEnum("focus_state", ["active", "completed", "cancelled"]);
export const operationState = pgEnum("operation_state", ["queued", "running", "ready", "failed", "expired", "cancelled"]);

export const users = pgTable("users", {
  id: text("id").primaryKey(),
  timeZone: varchar("time_zone", { length: 128 }).notNull().default("UTC"),
  deletedAt: optionalInstant("deleted_at"),
  createdAt: instant("created_at"),
  updatedAt: instant("updated_at"),
}, (t) => [index("users_live_idx").on(t.id).where(isNull(t.deletedAt))]);

export const courses = pgTable("courses", {
  id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  title: varchar("title", { length: 200 }).notNull(),
  code: varchar("code", { length: 64 }),
  archivedAt: optionalInstant("archived_at"),
  version: integer("version").notNull().default(1),
  createdAt: instant("created_at"), updatedAt: instant("updated_at"), deletedAt: optionalInstant("deleted_at"), purgeAfter: optionalInstant("purge_after"),
}, (t) => [index("courses_owner_live_idx").on(t.ownerId, t.updatedAt).where(isNull(t.deletedAt)), uniqueIndex("courses_owner_title_idx").on(t.ownerId, t.title).where(isNull(t.deletedAt))]);

export const assessments = pgTable("assessments", {
  id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  title: varchar("title", { length: 200 }).notNull(), details: text("details"), courseId: uuid("course_id"), dueDate: date("due_date"), dueTime: time("due_time", { precision: 0 }),
  status: academicStatus("status").notNull().default("open"), version: integer("version").notNull().default(1),
  createdAt: instant("created_at"), updatedAt: instant("updated_at"), deletedAt: optionalInstant("deleted_at"), purgeAfter: optionalInstant("purge_after"),
}, (t) => [foreignKeySameOwner("assessments_course_owner_fk", t.id, t.ownerId, t.courseId, courses), index("assessments_owner_due_idx").on(t.ownerId, t.dueDate, t.id).where(isNull(t.deletedAt))]);

export const tasks = pgTable("tasks", {
  id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  title: varchar("title", { length: 200 }).notNull(), details: text("details"), courseId: uuid("course_id"), assessmentId: uuid("assessment_id"), dueDate: date("due_date"), dueTime: time("due_time", { precision: 0 }),
  status: academicStatus("status").notNull().default("open"), version: integer("version").notNull().default(1),
  createdAt: instant("created_at"), updatedAt: instant("updated_at"), deletedAt: optionalInstant("deleted_at"), purgeAfter: optionalInstant("purge_after"),
}, (t) => [foreignKeySameOwner("tasks_course_owner_fk", t.id, t.ownerId, t.courseId, courses), foreignKeySameOwner("tasks_assessment_owner_fk", t.id, t.ownerId, t.assessmentId, assessments), index("tasks_owner_due_idx").on(t.ownerId, t.dueDate, t.id).where(isNull(t.deletedAt)), index("tasks_assessment_idx").on(t.ownerId, t.assessmentId).where(isNull(t.deletedAt))]);

export const timetableEntries = pgTable("timetable_entries", {
  id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), title: varchar("title", { length: 160 }).notNull(), details: text("details"), courseId: uuid("course_id"), kind: timetableKind("kind").notNull(), startDate: date("start_date").notNull(), endDate: date("end_date").notNull(), daysOfWeek: integer("days_of_week").array().notNull().default([]), startTime: time("start_time", { precision: 0 }).notNull(), endTime: time("end_time", { precision: 0 }).notNull(), version: integer("version").notNull().default(1), createdAt: instant("created_at"), updatedAt: instant("updated_at"), deletedAt: optionalInstant("deleted_at"), purgeAfter: optionalInstant("purge_after"),
}, (t) => [foreignKeySameOwner("timetable_course_owner_fk", t.id, t.ownerId, t.courseId, courses), index("timetable_owner_date_idx").on(t.ownerId, t.startDate, t.id).where(isNull(t.deletedAt))]);

export const timetableEntryExceptions = pgTable("timetable_entry_exceptions", { entryId: uuid("entry_id").notNull(), ownerId: text("owner_id").notNull(), occurrenceDate: date("occurrence_date").notNull(), createdAt: instant("created_at") }, (t) => [primaryKey({ columns: [t.entryId, t.occurrenceDate] }), foreignKeySameOwner("timetable_exception_owner_fk", t.entryId, t.ownerId, undefined, timetableEntries), index("timetable_exceptions_owner_idx").on(t.ownerId, t.entryId)]);

export const notes = pgTable("notes", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), title: varchar("title", { length: 160 }).notNull(), bodyMarkdown: text("body_markdown").notNull().default(""), courseId: uuid("course_id"), version: integer("version").notNull().default(1), createdAt: instant("created_at"), updatedAt: instant("updated_at"), deletedAt: optionalInstant("deleted_at"), purgeAfter: optionalInstant("purge_after") }, (t) => [foreignKeySameOwner("notes_course_owner_fk", t.id, t.ownerId, t.courseId, courses), index("notes_owner_updated_idx").on(t.ownerId, t.updatedAt, t.id).where(isNull(t.deletedAt))]);

export const files = pgTable("files", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), courseId: uuid("course_id"), kind: fileKind("kind").notNull(), displayName: varchar("display_name", { length: 180 }).notNull(), contentType: varchar("content_type", { length: 96 }).notNull(), sizeBytes: integer("size_bytes").notNull(), sha256: varchar("sha256", { length: 128 }), storageProvider: varchar("storage_provider", { length: 32 }).notNull(), storageBucketAlias: varchar("storage_bucket_alias", { length: 128 }).notNull(), storageKey: text("storage_key").notNull(), objectEtag: text("object_etag"), lifecycleState: fileLifecycleState("lifecycle_state").notNull().default("pending_upload"), extractionState: fileExtractionState("extraction_state").notNull().default("pending"), extractionVersion: varchar("extraction_version", { length: 64 }), pageCount: integer("page_count"), extractedChars: integer("extracted_chars").notNull().default(0), failureCode: varchar("failure_code", { length: 64 }), failureAttempt: integer("failure_attempt").notNull().default(0), uploadExpiresAt: timestamp("upload_expires_at", { withTimezone: true, mode: "date" }), readyAt: optionalInstant("ready_at"), version: integer("version").notNull().default(1), createdAt: instant("created_at"), updatedAt: instant("updated_at"), deletedAt: optionalInstant("deleted_at") }, (t) => [foreignKeySameOwner("files_course_owner_fk", t.id, t.ownerId, t.courseId, courses), uniqueIndex("files_owner_storage_key_idx").on(t.ownerId, t.storageKey), index("files_owner_state_idx").on(t.ownerId, t.lifecycleState, t.id)]);
export const fileChunks = pgTable("file_chunks", { id: id(), fileId: uuid("file_id").notNull(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), ordinal: integer("ordinal").notNull(), locator: jsonb("locator").notNull(), text: text("text").notNull(), characterCount: integer("character_count").notNull(), extractionVersion: varchar("extraction_version", { length: 64 }).notNull(), createdAt: instant("created_at") }, (t) => [foreignKeySameOwner("file_chunks_file_owner_fk", t.id, t.ownerId, t.fileId, files), uniqueIndex("file_chunks_file_ordinal_idx").on(t.fileId, t.ordinal), index("file_chunks_owner_idx").on(t.ownerId, t.fileId, t.ordinal)]);
export const fileProcessingJobs = pgTable("file_processing_jobs", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), fileId: uuid("file_id").notNull(), expectedVersion: integer("expected_version").notNull(), kind: varchar("kind", { length: 32 }).notNull(), attempts: integer("attempts").notNull().default(0), availableAt: instant("available_at"), leaseUntil: optionalInstant("lease_until"), failureCode: varchar("failure_code", { length: 64 }), createdAt: instant("created_at"), updatedAt: instant("updated_at") }, (t) => [foreignKeySameOwner("file_jobs_file_owner_fk", t.id, t.ownerId, t.fileId, files), uniqueIndex("file_jobs_file_version_kind_idx").on(t.fileId, t.expectedVersion, t.kind), index("file_jobs_owner_available_idx").on(t.ownerId, t.availableAt)]);

export const canvases = pgTable("canvases", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), title: varchar("title", { length: 160 }), state: canvasState("state").notNull().default("active"), version: integer("version").notNull().default(1), createdAt: instant("created_at"), updatedAt: instant("updated_at"), deletedAt: optionalInstant("deleted_at"), purgeAfter: optionalInstant("purge_after") }, (t) => [index("canvases_owner_updated_idx").on(t.ownerId, t.updatedAt, t.id).where(isNull(t.deletedAt))]);
export const canvasActivities = pgTable("canvas_activities", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), canvasId: uuid("canvas_id").notNull(), sequence: integer("sequence").notNull(), kind: varchar("kind", { length: 32 }).notNull(), payload: jsonb("payload").notNull(), createdAt: instant("created_at") }, (t) => [foreignKeySameOwner("canvas_activity_owner_fk", t.id, t.ownerId, t.canvasId, canvases), uniqueIndex("canvas_activities_sequence_idx").on(t.canvasId, t.sequence), index("canvas_activities_owner_idx").on(t.ownerId, t.canvasId, t.sequence)]);
export const generatedViews = pgTable("generated_views", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), canvasId: uuid("canvas_id").notNull(), requestActivityId: uuid("request_activity_id"), historySequence: integer("history_sequence").notNull(), catalogVersion: varchar("catalog_version", { length: 64 }).notNull(), schemaVersion: varchar("schema_version", { length: 64 }).notNull(), modelVersion: varchar("model_version", { length: 128 }).notNull(), promptVersion: varchar("prompt_version", { length: 64 }).notNull(), spec: jsonb("spec").notNull(), rationale: varchar("rationale", { length: 600 }), evidence: jsonb("evidence").notNull().default([]), createdAt: instant("created_at") }, (t) => [foreignKeySameOwner("generated_view_owner_fk", t.id, t.ownerId, t.canvasId, canvases), uniqueIndex("generated_views_history_idx").on(t.canvasId, t.historySequence), index("generated_views_owner_idx").on(t.ownerId, t.canvasId, t.historySequence)]);
export const canvasOperations = pgTable("canvas_operations", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), canvasId: uuid("canvas_id").notNull(), clientRequestId: varchar("client_request_id", { length: 200 }).notNull(), state: operationState("state").notNull().default("queued"), payload: jsonb("payload").notNull(), result: jsonb("result"), createdAt: instant("created_at"), updatedAt: instant("updated_at") }, (t) => [foreignKeySameOwner("canvas_operation_owner_fk", t.id, t.ownerId, t.canvasId, canvases), uniqueIndex("canvas_operations_owner_request_idx").on(t.ownerId, t.clientRequestId), index("canvas_operations_canvas_idx").on(t.canvasId, t.createdAt)]);

export const focusSessions = pgTable("focus_sessions", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), taskId: uuid("task_id"), courseId: uuid("course_id"), canvasId: uuid("canvas_id"), state: focusState("state").notNull(), plannedSeconds: integer("planned_seconds").notNull(), startedAt: instant("started_at"), endedAt: optionalInstant("ended_at"), version: integer("version").notNull().default(1), createdAt: instant("created_at"), updatedAt: instant("updated_at") }, (t) => [foreignKeySameOwner("focus_task_owner_fk", t.id, t.ownerId, t.taskId, tasks), foreignKeySameOwner("focus_course_owner_fk", t.id, t.ownerId, t.courseId, courses), foreignKeySameOwner("focus_canvas_owner_fk", t.id, t.ownerId, t.canvasId, canvases), uniqueIndex("focus_one_active_idx").on(t.ownerId).where(sql`${t.state} = 'active'`), index("focus_owner_history_idx").on(t.ownerId, t.createdAt)]);

export const notificationPreferences = pgTable("notification_preferences", { ownerId: text("owner_id").primaryKey().references(() => users.id, { onDelete: "cascade" }), inAppDeadlines: boolean("in_app_deadlines").notNull().default(true), inAppTimetable: boolean("in_app_timetable").notNull().default(true), inAppFocusCompletion: boolean("in_app_focus_completion").notNull().default(true), browserEnabled: boolean("browser_enabled").notNull().default(false), browserDeadlines: boolean("browser_deadlines").notNull().default(true), browserTimetable: boolean("browser_timetable").notNull().default(true), browserFocusCompletion: boolean("browser_focus_completion").notNull().default(true), quietStart: time("quiet_start", { precision: 0 }).notNull().default("22:00"), quietEnd: time("quiet_end", { precision: 0 }).notNull().default("07:00"), bodyMode: varchar("body_mode", { length: 16 }).notNull().default("generic"), version: integer("version").notNull().default(1), updatedAt: instant("updated_at") });
export const notificationEvents = pgTable("notification_events", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), eventKey: varchar("event_key", { length: 512 }).notNull(), kind: notificationKind("kind").notNull(), sourceType: varchar("source_type", { length: 32 }).notNull(), sourceId: uuid("source_id").notNull(), occurrenceKey: varchar("occurrence_key", { length: 128 }), scheduledFor: timestamp("scheduled_for", { withTimezone: true, mode: "date" }).notNull(), expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(), sourceTimeZone: varchar("source_time_zone", { length: 128 }).notNull(), ruleVersion: integer("rule_version").notNull(), state: notificationEventState("state").notNull().default("pending"), createdAt: instant("created_at"), updatedAt: instant("updated_at") }, (t) => [uniqueIndex("notification_events_owner_key_idx").on(t.ownerId, t.eventKey), index("notification_events_due_idx").on(t.ownerId, t.state, t.scheduledFor)]);
export const browserSubscriptions = pgTable("browser_subscriptions", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), endpointHash: varchar("endpoint_hash", { length: 128 }).notNull(), encryptedEndpoint: text("encrypted_endpoint").notNull(), encryptedKeys: text("encrypted_keys").notNull(), expiresAt: optionalInstant("expires_at"), lastSeenAt: optionalInstant("last_seen_at"), revokedAt: optionalInstant("revoked_at"), createdAt: instant("created_at"), updatedAt: instant("updated_at") }, (t) => [uniqueIndex("browser_subscriptions_owner_endpoint_idx").on(t.ownerId, t.endpointHash), index("browser_subscriptions_owner_live_idx").on(t.ownerId).where(isNull(t.revokedAt))]);
export const notificationDeliveries = pgTable("notification_deliveries", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), eventId: uuid("event_id").notNull(), subscriptionId: uuid("subscription_id"), channel: notificationChannel("channel").notNull(), deliveryKey: varchar("delivery_key", { length: 512 }).notNull(), state: deliveryState("state").notNull().default("pending"), attemptCount: integer("attempt_count").notNull().default(0), leaseUntil: optionalInstant("lease_until"), createdAt: instant("created_at"), updatedAt: instant("updated_at") }, (t) => [foreignKeySameOwner("notification_delivery_event_owner_fk", t.id, t.ownerId, t.eventId, notificationEvents), foreignKeySameOwner("notification_delivery_subscription_owner_fk", t.id, t.ownerId, t.subscriptionId, browserSubscriptions), uniqueIndex("notification_delivery_key_idx").on(t.ownerId, t.deliveryKey), index("notification_delivery_due_idx").on(t.ownerId, t.state, t.leaseUntil)]);

export const domainCommands = pgTable("domain_commands", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), canvasId: uuid("canvas_id").references(() => canvases.id, { onDelete: "cascade" }), sourceActivityId: uuid("source_activity_id"), idempotencyKey: varchar("idempotency_key", { length: 200 }).notNull(), commandVersion: integer("command_version").notNull(), kind: varchar("kind", { length: 96 }).notNull(), targetType: varchar("target_type", { length: 64 }), targetId: uuid("target_id"), expectedVersion: integer("expected_version"), state: commandState("state").notNull(), args: jsonb("args").notNull(), result: jsonb("result").notNull(), errorCode: varchar("error_code", { length: 64 }), createdAt: instant("created_at"), completedAt: optionalInstant("completed_at") }, (t) => [uniqueIndex("domain_commands_owner_idempotency_idx").on(t.ownerId, t.idempotencyKey), index("domain_commands_owner_created_idx").on(t.ownerId, t.createdAt), index("domain_commands_target_idx").on(t.ownerId, t.targetType, t.targetId)]);
export const undoTokens = pgTable("undo_tokens", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), commandId: uuid("command_id").notNull().references(() => domainCommands.id, { onDelete: "cascade" }), tokenHash: varchar("token_hash", { length: 128 }).notNull(), inverse: jsonb("inverse").notNull(), expectedVersion: integer("expected_version").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(), consumedAt: optionalInstant("consumed_at"), createdAt: instant("created_at") }, (t) => [uniqueIndex("undo_token_hash_idx").on(t.tokenHash), index("undo_owner_expiry_idx").on(t.ownerId, t.expiresAt)]);
export const outboxJobs = pgTable("outbox_jobs", { id: id(), ownerId: text("owner_id").references(() => users.id, { onDelete: "cascade" }), kind: varchar("kind", { length: 64 }).notNull(), aggregateType: varchar("aggregate_type", { length: 64 }).notNull(), aggregateId: uuid("aggregate_id"), payload: jsonb("payload").notNull(), availableAt: instant("available_at"), attempts: integer("attempts").notNull().default(0), leaseUntil: optionalInstant("lease_until"), completedAt: optionalInstant("completed_at"), createdAt: instant("created_at") }, (t) => [index("outbox_available_idx").on(t.availableAt, t.leaseUntil)]);
export const exportJobs = pgTable("export_jobs", { id: id(), ownerId: text("owner_id").notNull().references(() => users.id, { onDelete: "cascade" }), includeStructuredData: boolean("include_structured_data").notNull(), includeNotes: boolean("include_notes").notNull(), includeFiles: boolean("include_files").notNull(), state: operationState("state").notNull().default("queued"), archiveKey: text("archive_key"), failureCode: varchar("failure_code", { length: 64 }), createdAt: instant("created_at"), expiresAt: optionalInstant("expires_at") }, (t) => [index("export_jobs_owner_idx").on(t.ownerId, t.createdAt)]);
export const deletionJobs = pgTable("deletion_jobs", { id: id(), ownerId: text("owner_id").references(() => users.id, { onDelete: "set null" }), objectKeyHash: varchar("object_key_hash", { length: 128 }).notNull(), attempts: integer("attempts").notNull().default(0), availableAt: instant("available_at"), completedAt: optionalInstant("completed_at"), failureCode: varchar("failure_code", { length: 64 }), createdAt: instant("created_at") }, (t) => [index("deletion_jobs_available_idx").on(t.availableAt)]);

function foreignKeySameOwner(name: string, sourceId: any, sourceOwner: any, targetId: any, target: any) {
  return foreignKey({ name, columns: [targetId === undefined ? sourceId : targetId, sourceOwner], foreignColumns: [target.id, target.ownerId] });
}

export const schema = { users, courses, tasks, assessments, timetableEntries, timetableEntryExceptions, notes, files, fileChunks, fileProcessingJobs, canvases, canvasActivities, generatedViews, canvasOperations, focusSessions, notificationPreferences, notificationEvents, browserSubscriptions, notificationDeliveries, domainCommands, undoTokens, outboxJobs, exportJobs, deletionJobs };
