/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as DeadlinesRouteImport } from './routes/deadlines'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as CanvasIndexRouteImport } from './routes/canvas/index'
import { Route as CanvasTodayRouteImport } from './routes/canvas/today'
import { Route as ProtoIndexRouteImport } from './routes/proto/index'
import { Route as ProtoCatalogRouteImport } from './routes/proto/catalog'
import { Route as ProtoFocusRouteImport } from './routes/proto/focus'
import { Route as ProtoLifecycleRouteImport } from './routes/proto/lifecycle'
import { Route as ProtoAIndexRouteImport } from './routes/proto/a/index'
import { Route as ProtoATodayRouteImport } from './routes/proto/a/today'
import { Route as ProtoBIndexRouteImport } from './routes/proto/b/index'
import { Route as ProtoBTodayRouteImport } from './routes/proto/b/today'
import { Route as ProtoCIndexRouteImport } from './routes/proto/c/index'
import { Route as ProtoCTodayRouteImport } from './routes/proto/c/today'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlinesRoute = DeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIndexRoute = CanvasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CanvasRoute,
} as any)
const CanvasTodayRoute = CanvasTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => CanvasRoute,
} as any)
const ProtoIndexRoute = ProtoIndexRouteImport.update({
  id: '/proto/',
  path: '/proto/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoCatalogRoute = ProtoCatalogRouteImport.update({
  id: '/proto/catalog',
  path: '/proto/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoFocusRoute = ProtoFocusRouteImport.update({
  id: '/proto/focus',
  path: '/proto/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoLifecycleRoute = ProtoLifecycleRouteImport.update({
  id: '/proto/lifecycle',
  path: '/proto/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoAIndexRoute = ProtoAIndexRouteImport.update({
  id: '/proto/a/',
  path: '/proto/a/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoATodayRoute = ProtoATodayRouteImport.update({
  id: '/proto/a/today',
  path: '/proto/a/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoBIndexRoute = ProtoBIndexRouteImport.update({
  id: '/proto/b/',
  path: '/proto/b/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoBTodayRoute = ProtoBTodayRouteImport.update({
  id: '/proto/b/today',
  path: '/proto/b/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoCIndexRoute = ProtoCIndexRouteImport.update({
  id: '/proto/c/',
  path: '/proto/c/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoCTodayRoute = ProtoCTodayRouteImport.update({
  id: '/proto/c/today',
  path: '/proto/c/today',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/deadlines': typeof DeadlinesRoute
  '/focus': typeof FocusRoute
  '/notes': typeof NotesRoute
  '/tasks': typeof TasksRoute
  '/timetable': typeof TimetableRoute
  '/canvas/today': typeof CanvasTodayRoute
  '/proto/catalog': typeof ProtoCatalogRoute
  '/proto/focus': typeof ProtoFocusRoute
  '/proto/lifecycle': typeof ProtoLifecycleRoute
  '/canvas/': typeof CanvasIndexRoute
  '/proto/': typeof ProtoIndexRoute
  '/proto/a/today': typeof ProtoATodayRoute
  '/proto/b/today': typeof ProtoBTodayRoute
  '/proto/c/today': typeof ProtoCTodayRoute
  '/proto/a/': typeof ProtoAIndexRoute
  '/proto/b/': typeof ProtoBIndexRoute
  '/proto/c/': typeof ProtoCIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deadlines': typeof DeadlinesRoute
  '/focus': typeof FocusRoute
  '/notes': typeof NotesRoute
  '/tasks': typeof TasksRoute
  '/timetable': typeof TimetableRoute
  '/canvas/today': typeof CanvasTodayRoute
  '/proto/catalog': typeof ProtoCatalogRoute
  '/proto/focus': typeof ProtoFocusRoute
  '/proto/lifecycle': typeof ProtoLifecycleRoute
  '/canvas': typeof CanvasIndexRoute
  '/proto': typeof ProtoIndexRoute
  '/proto/a/today': typeof ProtoATodayRoute
  '/proto/b/today': typeof ProtoBTodayRoute
  '/proto/c/today': typeof ProtoCTodayRoute
  '/proto/a': typeof ProtoAIndexRoute
  '/proto/b': typeof ProtoBIndexRoute
  '/proto/c': typeof ProtoCIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/deadlines': typeof DeadlinesRoute
  '/focus': typeof FocusRoute
  '/notes': typeof NotesRoute
  '/tasks': typeof TasksRoute
  '/timetable': typeof TimetableRoute
  '/canvas/today': typeof CanvasTodayRoute
  '/proto/catalog': typeof ProtoCatalogRoute
  '/proto/focus': typeof ProtoFocusRoute
  '/proto/lifecycle': typeof ProtoLifecycleRoute
  '/canvas/': typeof CanvasIndexRoute
  '/proto/': typeof ProtoIndexRoute
  '/proto/a/today': typeof ProtoATodayRoute
  '/proto/b/today': typeof ProtoBTodayRoute
  '/proto/c/today': typeof ProtoCTodayRoute
  '/proto/a/': typeof ProtoAIndexRoute
  '/proto/b/': typeof ProtoBIndexRoute
  '/proto/c/': typeof ProtoCIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canvas'
    | '/deadlines'
    | '/focus'
    | '/notes'
    | '/tasks'
    | '/timetable'
    | '/canvas/today'
    | '/proto/catalog'
    | '/proto/focus'
    | '/proto/lifecycle'
    | '/canvas/'
    | '/proto/'
    | '/proto/a/today'
    | '/proto/b/today'
    | '/proto/c/today'
    | '/proto/a/'
    | '/proto/b/'
    | '/proto/c/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deadlines'
    | '/focus'
    | '/notes'
    | '/tasks'
    | '/timetable'
    | '/canvas/today'
    | '/proto/catalog'
    | '/proto/focus'
    | '/proto/lifecycle'
    | '/canvas'
    | '/proto'
    | '/proto/a/today'
    | '/proto/b/today'
    | '/proto/c/today'
    | '/proto/a'
    | '/proto/b'
    | '/proto/c'
  id:
    | '__root__'
    | '/'
    | '/canvas'
    | '/deadlines'
    | '/focus'
    | '/notes'
    | '/tasks'
    | '/timetable'
    | '/canvas/today'
    | '/proto/catalog'
    | '/proto/focus'
    | '/proto/lifecycle'
    | '/canvas/'
    | '/proto/'
    | '/proto/a/today'
    | '/proto/b/today'
    | '/proto/c/today'
    | '/proto/a/'
    | '/proto/b/'
    | '/proto/c/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasRoute: typeof CanvasRouteWithChildren
  DeadlinesRoute: typeof DeadlinesRoute
  FocusRoute: typeof FocusRoute
  NotesRoute: typeof NotesRoute
  TasksRoute: typeof TasksRoute
  TimetableRoute: typeof TimetableRoute
  ProtoCatalogRoute: typeof ProtoCatalogRoute
  ProtoFocusRoute: typeof ProtoFocusRoute
  ProtoLifecycleRoute: typeof ProtoLifecycleRoute
  ProtoIndexRoute: typeof ProtoIndexRoute
  ProtoATodayRoute: typeof ProtoATodayRoute
  ProtoBTodayRoute: typeof ProtoBTodayRoute
  ProtoCTodayRoute: typeof ProtoCTodayRoute
  ProtoAIndexRoute: typeof ProtoAIndexRoute
  ProtoBIndexRoute: typeof ProtoBIndexRoute
  ProtoCIndexRoute: typeof ProtoCIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlines': {
      id: '/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof DeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/': {
      id: '/canvas/'
      path: '/'
      fullPath: '/canvas/'
      preLoaderRoute: typeof CanvasIndexRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/canvas/today': {
      id: '/canvas/today'
      path: '/today'
      fullPath: '/canvas/today'
      preLoaderRoute: typeof CanvasTodayRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/proto/': {
      id: '/proto/'
      path: '/proto'
      fullPath: '/proto/'
      preLoaderRoute: typeof ProtoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/catalog': {
      id: '/proto/catalog'
      path: '/proto/catalog'
      fullPath: '/proto/catalog'
      preLoaderRoute: typeof ProtoCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/focus': {
      id: '/proto/focus'
      path: '/proto/focus'
      fullPath: '/proto/focus'
      preLoaderRoute: typeof ProtoFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/lifecycle': {
      id: '/proto/lifecycle'
      path: '/proto/lifecycle'
      fullPath: '/proto/lifecycle'
      preLoaderRoute: typeof ProtoLifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/a/': {
      id: '/proto/a/'
      path: '/proto/a'
      fullPath: '/proto/a/'
      preLoaderRoute: typeof ProtoAIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/a/today': {
      id: '/proto/a/today'
      path: '/proto/a/today'
      fullPath: '/proto/a/today'
      preLoaderRoute: typeof ProtoATodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/b/': {
      id: '/proto/b/'
      path: '/proto/b'
      fullPath: '/proto/b/'
      preLoaderRoute: typeof ProtoBIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/b/today': {
      id: '/proto/b/today'
      path: '/proto/b/today'
      fullPath: '/proto/b/today'
      preLoaderRoute: typeof ProtoBTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/c/': {
      id: '/proto/c/'
      path: '/proto/c'
      fullPath: '/proto/c/'
      preLoaderRoute: typeof ProtoCIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/c/today': {
      id: '/proto/c/today'
      path: '/proto/c/today'
      fullPath: '/proto/c/today'
      preLoaderRoute: typeof ProtoCTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CanvasRouteChildren {
  CanvasTodayRoute: typeof CanvasTodayRoute
  CanvasIndexRoute: typeof CanvasIndexRoute
}

const CanvasRouteChildren: CanvasRouteChildren = {
  CanvasTodayRoute: CanvasTodayRoute,
  CanvasIndexRoute: CanvasIndexRoute,
}

const CanvasRouteWithChildren =
  CanvasRoute._addFileChildren(CanvasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasRoute: CanvasRouteWithChildren,
  DeadlinesRoute: DeadlinesRoute,
  FocusRoute: FocusRoute,
  NotesRoute: NotesRoute,
  TasksRoute: TasksRoute,
  TimetableRoute: TimetableRoute,
  ProtoCatalogRoute: ProtoCatalogRoute,
  ProtoFocusRoute: ProtoFocusRoute,
  ProtoLifecycleRoute: ProtoLifecycleRoute,
  ProtoIndexRoute: ProtoIndexRoute,
  ProtoATodayRoute: ProtoATodayRoute,
  ProtoBTodayRoute: ProtoBTodayRoute,
  ProtoCTodayRoute: ProtoCTodayRoute,
  ProtoAIndexRoute: ProtoAIndexRoute,
  ProtoBIndexRoute: ProtoBIndexRoute,
  ProtoCIndexRoute: ProtoCIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
